server:
  port: 8080
  servlet:
    context-path: /generator
  tomcat:
    uri-encoding: UTF-8
    threads:
      max: 1000
      min-spare: 30

spring:
  profiles:
    active: dev
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB